export const airports = [
  // --- INDIAN AIRPORTS ---
  // Major Metros
  { city: "Delhi", name: "Indira Gandhi International", code: "DEL" },
  { city: "Mumbai", name: "Chhatrapati Shivaji Maharaj", code: "BOM" },
  { city: "Bangalore", name: "Kempegowda International", code: "BLR" },
  { city: "Chennai", name: "Chennai International", code: "MAA" },
  { city: "Hyderabad", name: "Rajiv Gandhi International", code: "HYD" },
  { city: "Kolkata", name: "Netaji Subhas Chandra Bose", code: "CCU" },

  // Major Cities
  { city: "Ahmedabad", name: "Sardar Vallabhbhai Patel", code: "AMD" },
  { city: "Pune", name: "Pune International", code: "PNQ" },
  { city: "Goa", name: "Dabolim", code: "GOI" },
  { city: "Goa (North)", name: "Manohar International", code: "GOX" },
  { city: "Jaipur", name: "Jaipur International", code: "JAI" },
  { city: "Lucknow", name: "Chaudhary Charan Singh", code: "LKO" },
  { city: "Kochi", name: "Cochin International", code: "COK" },
  { city: "Thiruvananthapuram", name: "Trivandrum International", code: "TRV" },
  { city: "Guwahati", name: "Lokpriya Gopinath Bordoloi", code: "GAU" },
  { city: "Bhubaneswar", name: "Biju Patnaik International", code: "BBI" },
  { city: "Indore", name: "Devi Ahilya Bai Holkar", code: "IDR" },
  { city: "Nagpur", name: "Dr. Babasaheb Ambedkar", code: "NAG" },
  { city: "Patna", name: "Jay Prakash Narayan", code: "PAT" },
  { city: "Varanasi", name: "Lal Bahadur Shastri", code: "VNS" },
  { city: "Srinagar", name: "Sheikh ul-Alam", code: "SXR" },
  { city: "Visakhapatnam", name: "Visakhapatnam International", code: "VTZ" },
  { city: "Chandigarh", name: "Shaheed Bhagat Singh", code: "IXC" },
  { city: "Amritsar", name: "Sri Guru Ram Dass Jee", code: "ATQ" },
  { city: "Coimbatore", name: "Coimbatore International", code: "CJB" },
  { city: "Mangalore", name: "Mangaluru International", code: "IXE" },
  { city: "Bagdogra", name: "Bagdogra", code: "IXB" },
  { city: "Ranchi", name: "Birsa Munda", code: "IXR" },
  { city: "Raipur", name: "Swami Vivekananda", code: "RPR" },
  { city: "Udaipur", name: "Maharana Pratap", code: "UDR" },
  { city: "Vadodara", name: "Vadodara", code: "BDQ" },
  { city: "Surat", name: "Surat International", code: "STV" },
  { city: "Tiruchirappalli", name: "Tiruchirappalli International", code: "TRZ" },
  { city: "Madurai", name: "Madurai", code: "IXM" },
  { city: "Vijayawada", name: "Vijayawada", code: "VGA" },
  { city: "Bhopal", name: "Raja Bhoj", code: "BHO" },
  { city: "Jodhpur", name: "Jodhpur", code: "JDH" },
  { city: "Port Blair", name: "Veer Savarkar International", code: "IXZ" },
  { city: "Leh", name: "Kushok Bakula Rimpochee", code: "IXL" },
  { city: "Jammu", name: "Jammu Civil Enclave", code: "IXJ" },
  { city: "Dehradun", name: "Jolly Grant", code: "DED" },
  { city: "Agartala", name: "Maharaja Bir Bikram", code: "IXA" },
  { city: "Imphal", name: "Bir Tikendrajit", code: "IMF" },
  { city: "Shillong", name: "Shillong", code: "SHL" },
  { city: "Dimapur", name: "Dimapur", code: "DMU" },
  { city: "Dibrugarh", name: "Dibrugarh", code: "DIB" },
  { city: "Silchar", name: "Silchar", code: "IXS" },
  { city: "Aizawl", name: "Lengpui", code: "AJL" },
  { city: "Gaya", name: "Gaya", code: "GAY" },
  { city: "Aurangabad", name: "Aurangabad", code: "IXU" },
  { city: "Rajkot", name: "Rajkot", code: "RAJ" },
  { city: "Hirasar", name: "Rajkot International", code: "HSR" },
  { city: "Jamnagar", name: "Jamnagar", code: "JGA" },
  { city: "Jaisalmer", name: "Jaisalmer", code: "JSA" },
  { city: "Kozhikode", name: "Calicut International", code: "CCJ" },
  { city: "Kannur", name: "Kannur International", code: "CNN" },
  { city: "Hubli", name: "Hubli", code: "HBX" },
  { city: "Belgaum", name: "Belagavi", code: "IXG" },
  { city: "Mysore", name: "Mysore", code: "MYQ" },
  { city: "Tirupati", name: "Tirupati", code: "TIR" },
  { city: "Rajahmundry", name: "Rajahmundry", code: "RJA" },
  { city: "Nashik", name: "Ozar", code: "ISK" },
  { city: "Shirdi", name: "Shirdi", code: "SAG" },
  { city: "Allahabad", name: "Prayagraj", code: "IXD" },
  { city: "Gorakhpur", name: "Gorakhpur", code: "GOP" },
  { city: "Agra", name: "Agra", code: "AGR" },
  { city: "Gwalior", name: "Rajmata Vijaya Raje Scindia", code: "GWL" },
  { city: "Jabalpur", name: "Jabalpur", code: "JLR" },
  { city: "Ayodhya", name: "Maharishi Valmiki International", code: "AYJ" },
  { city: "Diu", name: "Diu", code: "DIU" },
  { city: "Lakshadweep", name: "Agatti Island", code: "AGX" },

  // --- INTERNATIONAL AIRPORTS ---
  // North America
  { city: "New York", name: "John F. Kennedy", code: "JFK" },
  { city: "New York", name: "Newark Liberty", code: "EWR" },
  { city: "Los Angeles", name: "Los Angeles International", code: "LAX" },
  { city: "San Francisco", name: "San Francisco International", code: "SFO" },
  { city: "Chicago", name: "O'Hare International", code: "ORD" },
  { city: "Toronto", name: "Pearson International", code: "YYZ" },
  { city: "Vancouver", name: "Vancouver International", code: "YVR" },

  // Europe
  { city: "London", name: "Heathrow", code: "LHR" },
  { city: "London", name: "Gatwick", code: "LGW" },
  { city: "Paris", name: "Charles de Gaulle", code: "CDG" },
  { city: "Frankfurt", name: "Frankfurt", code: "FRA" },
  { city: "Amsterdam", name: "Schiphol", code: "AMS" },
  { city: "Zurich", name: "Zurich", code: "ZRH" },
  { city: "Munich", name: "Munich", code: "MUC" },
  { city: "Istanbul", name: "Istanbul", code: "IST" },

  // Middle East
  { city: "Dubai", name: "Dubai International", code: "DXB" },
  { city: "Abu Dhabi", name: "Abu Dhabi International", code: "AUH" },
  { city: "Doha", name: "Hamad International", code: "DOH" },

  // Asia Pacific
  { city: "Singapore", name: "Changi", code: "SIN" },
  { city: "Bangkok", name: "Suvarnabhumi", code: "BKK" },
  { city: "Tokyo", name: "Narita", code: "NRT" },
  { city: "Tokyo", name: "Haneda", code: "HND" },
  { city: "Hong Kong", name: "Hong Kong International", code: "HKG" },
  { city: "Kuala Lumpur", name: "Kuala Lumpur International", code: "KUL" },
  { city: "Seoul", name: "Incheon International", code: "ICN" },
  { city: "Sydney", name: "Kingsford Smith", code: "SYD" },
  { city: "Melbourne", name: "Tullamarine", code: "MEL" },
  { city: "Bali", name: "Ngurah Rai International", code: "DPS" },
  { city: "Maldives", name: "Velana International", code: "MLE" }
];